"""
EXR and TIFF Export Utilities

Handles high-dynamic-range image export with tone mapping.
"""

import os
from pathlib import Path
from typing import Optional, Literal


def export_to_exr(
    source_image_path: str,
    output_path: Optional[str] = None,
    bit_depth: Literal[16, 32] = 32,
    metadata: Optional[dict] = None
) -> str:
    """
    Export image to OpenEXR format.
    
    Args:
        source_image_path: Path to source image (JPEG/PNG)
        output_path: Optional output path
        bit_depth: 16 or 32 bit float
        metadata: Optional metadata dict to embed
        
    Returns:
        Path to exported EXR file
    """
    try:
        import OpenEXR
        import Imath
        from PIL import Image
        import numpy as np
        
        # Load source image
        img = Image.open(source_image_path).convert('RGB')
        img_array = np.array(img).astype(np.float32) / 255.0
        
        # Prepare output path
        if output_path is None:
            output_path = Path(source_image_path).with_suffix('.exr')
        
        # Create EXR header
        height, width = img_array.shape[:2]
        header = OpenEXR.Header(width, height)
        
        # Add metadata
        if metadata:
            for key, value in metadata.items():
                header[key] = str(value)
        
        # Set pixel type
        if bit_depth == 16:
            pixel_type = Imath.PixelType(Imath.PixelType.HALF)
        else:
            pixel_type = Imath.PixelType(Imath.PixelType.FLOAT)
        
        # Write EXR
        exr = OpenEXR.OutputFile(str(output_path), header)
        
        r = img_array[:,:,0].tobytes()
        g = img_array[:,:,1].tobytes()
        b = img_array[:,:,2].tobytes()
        
        exr.writePixels({'R': r, 'G': g, 'B': b})
        exr.close()
        
        return str(output_path)
        
    except ImportError:
        print("Warning: OpenEXR not installed. Install with: pip install openexr")
        return source_image_path
    except Exception as e:
        print(f"EXR export failed: {e}")
        return source_image_path


def export_to_tiff(
    source_image_path: str,
    output_path: Optional[str] = None,
    bit_depth: Literal[8, 16] = 16,
    compression: str = "lzw"
) -> str:
    """
    Export image to TIFF format.
    
    Args:
        source_image_path: Path to source image
        output_path: Optional output path
        bit_depth: 8 or 16 bit
        compression: Compression method (lzw, none, jpeg)
        
    Returns:
        Path to exported TIFF file
    """
    try:
        from PIL import Image
        
        img = Image.open(source_image_path)
        
        if output_path is None:
            output_path = Path(source_image_path).with_suffix('.tiff')
        
        # Convert to 16-bit if requested
        if bit_depth == 16:
            img = img.convert('I;16')
        
        img.save(
            output_path,
            'TIFF',
            compression=compression,
            tiffinfo={
                270: "Generated by StudioFlow FIBO",  # ImageDescription
                305: "StudioFlow v0.1.0",  # Software
            }
        )
        
        return str(output_path)
        
    except Exception as e:
        print(f"TIFF export failed: {e}")
        return source_image_path


def apply_tone_mapping(
    input_path: str,
    output_path: str,
    method: Literal["aces", "reinhard", "exposure"] = "aces",
    exposure: float = 0.0
) -> str:
    """
    Apply tone mapping to HDR image.
    
    Args:
        input_path: Path to HDR image (EXR/TIFF)
        output_path: Path for tone-mapped output
        method: Tone mapping algorithm
        exposure: Exposure adjustment in stops
        
    Returns:
        Path to tone-mapped image
    """
    try:
        from PIL import Image
        import numpy as np
        
        img = Image.open(input_path)
        img_array = np.array(img).astype(np.float32)
        
        # Apply exposure
        if exposure != 0.0:
            img_array *= (2 ** exposure)
        
        # Apply tone mapping
        if method == "aces":
            img_array = aces_tonemap(img_array)
        elif method == "reinhard":
            img_array = reinhard_tonemap(img_array)
        elif method == "exposure":
            img_array = np.clip(img_array, 0, 1)
        
        # Convert to 8-bit
        img_array = (img_array * 255).astype(np.uint8)
        
        output_img = Image.fromarray(img_array)
        output_img.save(output_path, quality=95)
        
        return output_path
        
    except Exception as e:
        print(f"Tone mapping failed: {e}")
        return input_path


def aces_tonemap(hdr_image: 'np.ndarray') -> 'np.ndarray':
    """ACES filmic tone mapping."""
    a = 2.51
    b = 0.03
    c = 2.43
    d = 0.59
    e = 0.14
    return np.clip((hdr_image * (a * hdr_image + b)) / (hdr_image * (c * hdr_image + d) + e), 0, 1)


def reinhard_tonemap(hdr_image: 'np.ndarray') -> 'np.ndarray':
    """Simple Reinhard tone mapping."""
    return hdr_image / (1.0 + hdr_image)
